### ISSUE TITLE
Missing onchange?

### ISSUE THREAD

**Issue by LiveNathan** [wimdeblauwe/modern-frontends-with-htmx-sources#1]
Chapter 5 says, "There is an onchange handler that submits the form...”

But in the fragments file, I don't see onchange.

https://github.com/wimdeblauwe/modern-frontends-with-htmx-sources/blob/c25ae34d08f76f3f9eece634e2b0070c405c6e44/chapter05%20-%20todomvc/src/main/resources/templates/fragments.html#L8

**Comment by LiveNathan** [comment]
Never mind. Just finished the chapter and realize that the code here is the finished state. If I knew how to delete an issue, I would. :)

**Comment by wimdeblauwe** [comment]
No worries, glad you figured it out :)
