### ISSUE TITLE
How to handle htmx warnings in Intellij

### ISSUE THREAD

**Issue by LiveNathan** [wimdeblauwe/modern-frontends-with-htmx-sources#2]
Hi Wim! How do you handle these warnings? 

![2024-04-03 at 09 22 31@2x](https://github.com/wimdeblauwe/modern-frontends-with-htmx-sources/assets/60303904/64bdfda3-44be-4760-8607-8957604f21cb)

https://github.com/wimdeblauwe/modern-frontends-with-htmx-sources/blob/c25ae34d08f76f3f9eece634e2b0070c405c6e44/chapter09%20-%20contacts/src/main/resources/templates/contacts/edit.html#L37

**Comment by wimdeblauwe** [comment]
You can click on "Add hx:confirm to custom html attributes" to have the warning go away.
