### ISSUE TITLE
Issues with resolving templates on other pages

### ISSUE THREAD

**Issue by selop** [wimdeblauwe/modern-frontends-with-htmx-sources#4]
Hi, this might be a thymeleaf + spring boot issue but I've encountered it while working with the HTMX book. 

## Issue Summary
I'm working on a prototype with mostly static content. It's an portfolio/blog style MPA with a welcome page and other pages such as about etc.

I have generated the project using `ttcli`. I've worked w/o issues on the welcome page using Tailwind/daisyUI and started to work on other pages. When I'm using `th:href` to direct to other pages the template I'm refering to in my controller is not found leading to a redirect to /error. 

A very similar behavior is implemented chapter09 - contacts where the initial page load is redirecting to another page.
The chapter09 sample works fine and when I extend it with the content of my reproducer it also works. 

## Reproducer 

https://github.com/selop/spring-boot-htmx-thymeleaf-redirect-reproducer

Can you confirm the issue using the reproducer?

**Comment by wimdeblauwe** [comment]
I get a 404 trying to access that URL. Is the repository public?

**Comment by selop** [comment]
Sorry for that I've changed the visibility

**Comment by wimdeblauwe** [comment]
The issue is that you need to have your main `@SpringBootApplication` class at your root package and the controllers below that, otherwise, Spring Boot will not find them.

If I move `com.example.redirect_reproducer.DemoApplication` to `com.example.DemoApplication` and restart the application, everything works fine.

**Comment by selop** [comment]
Thanks for the fast reply. I see this is an issue with how I've setup the input for ttcli and how the spring initialzr API returns the project package name - see https://github.com/wimdeblauwe/ttcli/blob/main/src/main/java/io/github/wimdeblauwe/ttcli/java/JavaCodeInitService.java

Do you see a need to change this in ttcli? I've would try to file a PR.

**Comment by wimdeblauwe** [comment]
You are always welcome to file a PR.

**Comment by selop** [comment]
It seems you were faster than me :D https://github.com/wimdeblauwe/ttcli/commit/8cd6036922ac8ba8ce2fcd9644b27597627873dd

Closing this one for sure.
