### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by smunoze** [wimdeblauwe/modern-frontends-with-htmx-sources#5]
Hi Wim, hop you are great.

Currently Im having and issue with css, they are not working. My guess is that the css in not correct when I generate the build I would leave the screenshot for the current source and the output css files.

node version: v18
using kotlin (webjar works 👍 ) 

[input css file]
<img width="1409" alt="image" src="https://github.com/user-attachments/assets/a4f59ea3-e79f-42af-9586-d4d9b44c3e74">

[output css file]
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/94e23ef3-8040-4ae5-9994-f6c4d1f5f1bc">

[browser content]<img width="1506" alt="image" src="https://github.com/user-attachments/assets/6bee6463-94d8-4e45-be9e-d09a7847aec5">

Thanx!

**Comment by smunoze** [comment]
my bad!, the file postcss.config.js was named as postcss-config.js, that was the issue

**Comment by smunoze** [comment]
my bad!, the file postcss.config.js was named as postcss-config.js, that was the issue

**Comment by wimdeblauwe** [comment]
Glad you found it!
