### ISSUE TITLE
Building project Question - Gulp.js

### ISSUE THREAD

**Issue by smunoz-tech** [wimdeblauwe/modern-frontends-with-htmx-sources#6]
Hi Wim, I hope you're doing well. The new book is great. However, I have a question: why aren't you using gulp.js for building the project in this book, like you did in the book "Taming Thymeleaf"?

Regards

**Comment by wimdeblauwe** [comment]
The Gulp based build had a lot of dependencies that where having security issues or no longer actively maintained. For that reason, I switched to using npm scripts instead. More recently, I am now using Vite instead which works really great. If you use [ttcli](https://github.com/wimdeblauwe/ttcli), you can select Vite now. But the npm scripts also still work fine.

**Comment by smunoz-tech** [comment]
Thx Wim for the clarification and for sharing your knowledge.
